name: Frisby tests
on: 
 push:
   branches:
     - master
jobs:
 Frisby-Test:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout GitCode
       uses: actions/checkout@v3
     - name: Install deps
       run: npm i
     - name: Start frisby test
       run: npm run test
       env:
        POSTMAN_SECRET_KEY: ${{ secrets.POSTMAN_SECRET_KEY }}
        POSTMAN_WORKSPACE_ID: ${{ secrets.POSTMAN_WORKSPACE_ID }}
        POSTMAN_GITHUB_AUTH_TOKEN: ${{ secrets.POSTMAN_GITHUB_AUTH_TOKEN }}